### ISSUE TITLE
 Incompatible shapes: [12,216,256] vs. [12,208,256]

### ISSUE THREAD

**Issue by yimingfei** [chuckyee/cardiac-segmentation#9]
Traceback (most recent call last):
  File "scripts/train.py", line 164, in <module>
    train()
  File "scripts/train.py", line 159, in train
    verbose=2)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1834, in fit_generator
    class_weight=class_weight)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1560, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2268, in __call__
    **self.session_kwargs)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [12,216,256] vs. [12,208,256]
	 [[Node: Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"](ArgMax, ArgMax_1)]]
	 [[Node: Mean_6/_39 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3498_Mean_6", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'Equal', defined at:
  File "scripts/train.py", line 164, in <module>
    train()
  File "scripts/train.py", line 125, in train
    m.compile(optimizer=optimizer, loss=lossfunc, metrics=metrics)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 883, in compile
    append_metric(i, 'acc', masked_fn(y_true, y_pred, mask=masks[i]))
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 494, in masked
    score_array = fn(y_true, y_pred)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/keras/metrics.py", line 26, in categorical_accuracy
    K.argmax(y_pred, axis=-1)),
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1516, in equal
    return tf.equal(x, y)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 721, in equal
    result = _op_def_lib.apply_op("Equal", x=x, y=y, name=name)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/yuzhuo/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [12,216,256] vs. [12,208,256]
	 [[Node: Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"](ArgMax, ArgMax_1)]]
	 [[Node: Mean_6/_39 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3498_Mean_6", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by DL-Alva** [comment]
Hi, I have met the same problem. Have you solved your problems? Thank you for your reply.
